server:
  port: 19527
  servlet:
    context-path: /
spring:
  rabbitmq:
    host: 192.168.11.60
    port: 5672
    password: 123456
    username: admin

  datasource:
    initialization-mode: ALWAYS
    platform: primary
    continue-on-error: true

    primary:
      driverClassName: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.8.45:1521:ora11g
      username: cdb_archive
      password: content4me
      test-on-borrow: true
      validation-query: select 1 from dual
      test-while-idle: true
